package BLL;
// Generated 14/set/2017 0:29:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int nif;
     private String nome;
     private String localidade;
     private Integer contacto;
     private Set vendas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int nif) {
        this.nif = nif;
    }
    public Cliente(int nif, String nome, String localidade, Integer contacto, Set vendas) {
       this.nif = nif;
       this.nome = nome;
       this.localidade = localidade;
       this.contacto = contacto;
       this.vendas = vendas;
    }
   
    public int getNif() {
        return this.nif;
    }
    
    public void setNif(int nif) {
        this.nif = nif;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getLocalidade() {
        return this.localidade;
    }
    
    public void setLocalidade(String localidade) {
        this.localidade = localidade;
    }
    public Integer getContacto() {
        return this.contacto;
    }
    
    public void setContacto(Integer contacto) {
        this.contacto = contacto;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }




}


