package BLL;
// Generated 13/set/2017 17:26:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Entidade generated by hbm2java
 */
public class Entidade  implements java.io.Serializable {


     private int nipc;
     private Integer cae;
     private String morada;
     private Float capitalSocial;
     private String nomeComercial;
     private Set recibos = new HashSet(0);

    public Entidade() {
    }

	
    public Entidade(int nipc) {
        this.nipc = nipc;
    }
    public Entidade(int nipc, Integer cae, String morada, Float capitalSocial, String nomeComercial, Set recibos) {
       this.nipc = nipc;
       this.cae = cae;
       this.morada = morada;
       this.capitalSocial = capitalSocial;
       this.nomeComercial = nomeComercial;
       this.recibos = recibos;
    }
   
    public int getNipc() {
        return this.nipc;
    }
    
    public void setNipc(int nipc) {
        this.nipc = nipc;
    }
    public Integer getCae() {
        return this.cae;
    }
    
    public void setCae(Integer cae) {
        this.cae = cae;
    }
    public String getMorada() {
        return this.morada;
    }
    
    public void setMorada(String morada) {
        this.morada = morada;
    }
    public Float getCapitalSocial() {
        return this.capitalSocial;
    }
    
    public void setCapitalSocial(Float capitalSocial) {
        this.capitalSocial = capitalSocial;
    }
    public String getNomeComercial() {
        return this.nomeComercial;
    }
    
    public void setNomeComercial(String nomeComercial) {
        this.nomeComercial = nomeComercial;
    }
    public Set getRecibos() {
        return this.recibos;
    }
    
    public void setRecibos(Set recibos) {
        this.recibos = recibos;
    }




}


