package BLL;
// Generated 14/set/2017 0:29:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Fornecedor generated by hbm2java
 */
public class Fornecedor  implements java.io.Serializable {


     private int fornecedorId;
     private String nome;
     private String morada;
     private Integer contacto;
     private Set encomendas = new HashSet(0);
     private Set produtoFornecedors = new HashSet(0);

    public Fornecedor() {
    }

	
    public Fornecedor(int fornecedorId) {
        this.fornecedorId = fornecedorId;
    }
    public Fornecedor(int fornecedorId, String nome, String morada, Integer contacto, Set encomendas, Set produtoFornecedors) {
       this.fornecedorId = fornecedorId;
       this.nome = nome;
       this.morada = morada;
       this.contacto = contacto;
       this.encomendas = encomendas;
       this.produtoFornecedors = produtoFornecedors;
    }
   
    public int getFornecedorId() {
        return this.fornecedorId;
    }
    
    public void setFornecedorId(int fornecedorId) {
        this.fornecedorId = fornecedorId;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getMorada() {
        return this.morada;
    }
    
    public void setMorada(String morada) {
        this.morada = morada;
    }
    public Integer getContacto() {
        return this.contacto;
    }
    
    public void setContacto(Integer contacto) {
        this.contacto = contacto;
    }
    public Set getEncomendas() {
        return this.encomendas;
    }
    
    public void setEncomendas(Set encomendas) {
        this.encomendas = encomendas;
    }
    public Set getProdutoFornecedors() {
        return this.produtoFornecedors;
    }
    
    public void setProdutoFornecedors(Set produtoFornecedors) {
        this.produtoFornecedors = produtoFornecedors;
    }




}


