package BLL;
// Generated 13/set/2017 17:26:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Funcionario generated by hbm2java
 */
public class Funcionario  implements java.io.Serializable {


     private Integer funcionairoId;
     private String password;
     private String nome;
     private String morada;
     private Integer telefone;
     private String EMail;
     private byte[] tipo;
     private String username;
     private Set vendas = new HashSet(0);
     private Set encomendas = new HashSet(0);
     private Set registas = new HashSet(0);
     private Set reposicaos = new HashSet(0);

    public Funcionario() {
    }

	
    public Funcionario(String password, String nome, String username) {
        this.password = password;
        this.nome = nome;
        this.username = username;
    }
    public Funcionario(String password, String nome, String morada, Integer telefone, String EMail, byte[] tipo, String username, Set vendas, Set encomendas, Set registas, Set reposicaos) {
       this.password = password;
       this.nome = nome;
       this.morada = morada;
       this.telefone = telefone;
       this.EMail = EMail;
       this.tipo = tipo;
       this.username = username;
       this.vendas = vendas;
       this.encomendas = encomendas;
       this.registas = registas;
       this.reposicaos = reposicaos;
    }
   
    public Integer getFuncionairoId() {
        return this.funcionairoId;
    }
    
    public void setFuncionairoId(Integer funcionairoId) {
        this.funcionairoId = funcionairoId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getMorada() {
        return this.morada;
    }
    
    public void setMorada(String morada) {
        this.morada = morada;
    }
    public Integer getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(Integer telefone) {
        this.telefone = telefone;
    }
    public String getEMail() {
        return this.EMail;
    }
    
    public void setEMail(String EMail) {
        this.EMail = EMail;
    }
    public byte[] getTipo() {
        return this.tipo;
    }
    
    public void setTipo(byte[] tipo) {
        this.tipo = tipo;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public Set getVendas() {
        return this.vendas;
    }
    
    public void setVendas(Set vendas) {
        this.vendas = vendas;
    }
    public Set getEncomendas() {
        return this.encomendas;
    }
    
    public void setEncomendas(Set encomendas) {
        this.encomendas = encomendas;
    }
    public Set getRegistas() {
        return this.registas;
    }
    
    public void setRegistas(Set registas) {
        this.registas = registas;
    }
    public Set getReposicaos() {
        return this.reposicaos;
    }
    
    public void setReposicaos(Set reposicaos) {
        this.reposicaos = reposicaos;
    }




}


