package BLL;
// Generated 13/set/2017 17:26:29 by Hibernate Tools 4.3.1



/**
 * Gestor generated by hbm2java
 */
public class Gestor  implements java.io.Serializable {


     private int gestorId;
     private String password;

    public Gestor() {
    }

    public Gestor(int gestorId, String password) {
       this.gestorId = gestorId;
       this.password = password;
    }
   
    public int getGestorId() {
        return this.gestorId;
    }
    
    public void setGestorId(int gestorId) {
        this.gestorId = gestorId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


