package BLL;
// Generated 14/set/2017 0:29:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Inventario generated by hbm2java
 */
public class Inventario  implements java.io.Serializable {


     private int inventarioId;
     private String desc;
     private Set prodInvents = new HashSet(0);

    public Inventario() {
    }

	
    public Inventario(int inventarioId) {
        this.inventarioId = inventarioId;
    }
    public Inventario(int inventarioId, String desc, Set prodInvents) {
       this.inventarioId = inventarioId;
       this.desc = desc;
       this.prodInvents = prodInvents;
    }
   
    public int getInventarioId() {
        return this.inventarioId;
    }
    
    public void setInventarioId(int inventarioId) {
        this.inventarioId = inventarioId;
    }
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }
    public Set getProdInvents() {
        return this.prodInvents;
    }
    
    public void setProdInvents(Set prodInvents) {
        this.prodInvents = prodInvents;
    }




}


