package BLL;
// Generated 13/set/2017 17:26:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Iva generated by hbm2java
 */
public class Iva  implements java.io.Serializable {


     private int ivaId;
     private Float valor;
     private Set produtos = new HashSet(0);

    public Iva() {
    }

	
    public Iva(int ivaId) {
        this.ivaId = ivaId;
    }
    public Iva(int ivaId, Float valor, Set produtos) {
       this.ivaId = ivaId;
       this.valor = valor;
       this.produtos = produtos;
    }
   
    public int getIvaId() {
        return this.ivaId;
    }
    
    public void setIvaId(int ivaId) {
        this.ivaId = ivaId;
    }
    public Float getValor() {
        return this.valor;
    }
    
    public void setValor(Float valor) {
        this.valor = valor;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }




}


