package BLL;
// Generated 14/set/2017 0:29:34 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Iva generated by hbm2java
 */
public class Iva  implements java.io.Serializable {


     private Integer ivaId;
     private Float valor;
     private Set produtos = new HashSet(0);

    public Iva() {
    }

    public Iva(Float valor, Set produtos) {
       this.valor = valor;
       this.produtos = produtos;
    }
   
    public Integer getIvaId() {
        return this.ivaId;
    }
    
    public void setIvaId(Integer ivaId) {
        this.ivaId = ivaId;
    }
    public Float getValor() {
        return this.valor;
    }
    
    public void setValor(Float valor) {
        this.valor = valor;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }




}


