package BLL;
// Generated 13/set/2017 17:26:29 by Hibernate Tools 4.3.1



/**
 * MovimentoReposicao generated by hbm2java
 */
public class MovimentoReposicao  implements java.io.Serializable {


     private MovimentoReposicaoId id;
     private Produto produto;
     private Reposicao reposicao;
     private Integer quantidade;

    public MovimentoReposicao() {
    }

	
    public MovimentoReposicao(MovimentoReposicaoId id, Produto produto, Reposicao reposicao) {
        this.id = id;
        this.produto = produto;
        this.reposicao = reposicao;
    }
    public MovimentoReposicao(MovimentoReposicaoId id, Produto produto, Reposicao reposicao, Integer quantidade) {
       this.id = id;
       this.produto = produto;
       this.reposicao = reposicao;
       this.quantidade = quantidade;
    }
   
    public MovimentoReposicaoId getId() {
        return this.id;
    }
    
    public void setId(MovimentoReposicaoId id) {
        this.id = id;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Reposicao getReposicao() {
        return this.reposicao;
    }
    
    public void setReposicao(Reposicao reposicao) {
        this.reposicao = reposicao;
    }
    public Integer getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
    }




}


