package BLL;
// Generated 14/set/2017 0:29:34 by Hibernate Tools 4.3.1



/**
 * MovimentoVenda generated by hbm2java
 */
public class MovimentoVenda  implements java.io.Serializable {


     private MovimentoVendaId id;
     private Produto produto;
     private Venda venda;
     private Integer quantidade;
     private Float preco;
     private Float iva;

    public MovimentoVenda() {
    }

	
    public MovimentoVenda(MovimentoVendaId id, Produto produto, Venda venda) {
        this.id = id;
        this.produto = produto;
        this.venda = venda;
    }
    public MovimentoVenda(MovimentoVendaId id, Produto produto, Venda venda, Integer quantidade, Float preco, Float iva) {
       this.id = id;
       this.produto = produto;
       this.venda = venda;
       this.quantidade = quantidade;
       this.preco = preco;
       this.iva = iva;
    }
   
    public MovimentoVendaId getId() {
        return this.id;
    }
    
    public void setId(MovimentoVendaId id) {
        this.id = id;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Venda getVenda() {
        return this.venda;
    }
    
    public void setVenda(Venda venda) {
        this.venda = venda;
    }
    public Integer getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
    }
    public Float getPreco() {
        return this.preco;
    }
    
    public void setPreco(Float preco) {
        this.preco = preco;
    }
    public Float getIva() {
        return this.iva;
    }
    
    public void setIva(Float iva) {
        this.iva = iva;
    }




}


