package BLL;
// Generated 14/set/2017 0:29:34 by Hibernate Tools 4.3.1



/**
 * ProdutoFornecedor generated by hbm2java
 */
public class ProdutoFornecedor  implements java.io.Serializable {


     private ProdutoFornecedorId id;
     private Fornecedor fornecedor;
     private Produto produto;
     private Float precoCompra;

    public ProdutoFornecedor() {
    }

	
    public ProdutoFornecedor(ProdutoFornecedorId id, Fornecedor fornecedor, Produto produto) {
        this.id = id;
        this.fornecedor = fornecedor;
        this.produto = produto;
    }
    public ProdutoFornecedor(ProdutoFornecedorId id, Fornecedor fornecedor, Produto produto, Float precoCompra) {
       this.id = id;
       this.fornecedor = fornecedor;
       this.produto = produto;
       this.precoCompra = precoCompra;
    }
   
    public ProdutoFornecedorId getId() {
        return this.id;
    }
    
    public void setId(ProdutoFornecedorId id) {
        this.id = id;
    }
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Float getPrecoCompra() {
        return this.precoCompra;
    }
    
    public void setPrecoCompra(Float precoCompra) {
        this.precoCompra = precoCompra;
    }




}


