package BLL;
// Generated 14/set/2017 0:29:34 by Hibernate Tools 4.3.1



/**
 * ProdutoEncomendaId generated by hbm2java
 */
public class ProdutoEncomendaId  implements java.io.Serializable {


     private int idProduto;
     private int idEncomenda;

    public ProdutoEncomendaId() {
    }

    public ProdutoEncomendaId(int idProduto, int idEncomenda) {
       this.idProduto = idProduto;
       this.idEncomenda = idEncomenda;
    }
   
    public int getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(int idProduto) {
        this.idProduto = idProduto;
    }
    public int getIdEncomenda() {
        return this.idEncomenda;
    }
    
    public void setIdEncomenda(int idEncomenda) {
        this.idEncomenda = idEncomenda;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProdutoEncomendaId) ) return false;
		 ProdutoEncomendaId castOther = ( ProdutoEncomendaId ) other; 
         
		 return (this.getIdProduto()==castOther.getIdProduto())
 && (this.getIdEncomenda()==castOther.getIdEncomenda());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdProduto();
         result = 37 * result + this.getIdEncomenda();
         return result;
   }   


}


