package BLL;
// Generated 13/set/2017 17:26:29 by Hibernate Tools 4.3.1



/**
 * ProdutoEncomenda generated by hbm2java
 */
public class ProdutoEncomenda  implements java.io.Serializable {


     private ProdutoEncomendaId id;
     private Encomenda encomenda;
     private Produto produto;
     private Integer quantidade;

    public ProdutoEncomenda() {
    }

	
    public ProdutoEncomenda(ProdutoEncomendaId id, Encomenda encomenda, Produto produto) {
        this.id = id;
        this.encomenda = encomenda;
        this.produto = produto;
    }
    public ProdutoEncomenda(ProdutoEncomendaId id, Encomenda encomenda, Produto produto, Integer quantidade) {
       this.id = id;
       this.encomenda = encomenda;
       this.produto = produto;
       this.quantidade = quantidade;
    }
   
    public ProdutoEncomendaId getId() {
        return this.id;
    }
    
    public void setId(ProdutoEncomendaId id) {
        this.id = id;
    }
    public Encomenda getEncomenda() {
        return this.encomenda;
    }
    
    public void setEncomenda(Encomenda encomenda) {
        this.encomenda = encomenda;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Integer getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
    }




}


