package BLL;
// Generated 14/set/2017 0:29:34 by Hibernate Tools 4.3.1



/**
 * ProdInvent generated by hbm2java
 */
public class ProdInvent  implements java.io.Serializable {


     private ProdInventId id;
     private Inventario inventario;
     private Produto produto;
     private Integer quantidade;

    public ProdInvent() {
    }

	
    public ProdInvent(ProdInventId id, Inventario inventario, Produto produto) {
        this.id = id;
        this.inventario = inventario;
        this.produto = produto;
    }
    public ProdInvent(ProdInventId id, Inventario inventario, Produto produto, Integer quantidade) {
       this.id = id;
       this.inventario = inventario;
       this.produto = produto;
       this.quantidade = quantidade;
    }
   
    public ProdInventId getId() {
        return this.id;
    }
    
    public void setId(ProdInventId id) {
        this.id = id;
    }
    public Inventario getInventario() {
        return this.inventario;
    }
    
    public void setInventario(Inventario inventario) {
        this.inventario = inventario;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Integer getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
    }




}


