package BLL;
// Generated 13/set/2017 17:26:29 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private int produtoId;
     private Categoria categoria;
     private Iva iva;
     private String descricao;
     private String precoVenda;
     private String nome;
     private Set registaProdutos = new HashSet(0);
     private Set movimentoVendas = new HashSet(0);
     private Set prodInvents = new HashSet(0);
     private Set produtoFornecedors = new HashSet(0);
     private Set produtoEncomendas = new HashSet(0);
     private Set movimentoReposicaos = new HashSet(0);

    public Produto() {
    }

	
    public Produto(int produtoId, Categoria categoria) {
        this.produtoId = produtoId;
        this.categoria = categoria;
    }
    public Produto(int produtoId, Categoria categoria, Iva iva, String descricao, String precoVenda, String nome, Set registaProdutos, Set movimentoVendas, Set prodInvents, Set produtoFornecedors, Set produtoEncomendas, Set movimentoReposicaos) {
       this.produtoId = produtoId;
       this.categoria = categoria;
       this.iva = iva;
       this.descricao = descricao;
       this.precoVenda = precoVenda;
       this.nome = nome;
       this.registaProdutos = registaProdutos;
       this.movimentoVendas = movimentoVendas;
       this.prodInvents = prodInvents;
       this.produtoFornecedors = produtoFornecedors;
       this.produtoEncomendas = produtoEncomendas;
       this.movimentoReposicaos = movimentoReposicaos;
    }
   
    public int getProdutoId() {
        return this.produtoId;
    }
    
    public void setProdutoId(int produtoId) {
        this.produtoId = produtoId;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public Iva getIva() {
        return this.iva;
    }
    
    public void setIva(Iva iva) {
        this.iva = iva;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public String getPrecoVenda() {
        return this.precoVenda;
    }
    
    public void setPrecoVenda(String precoVenda) {
        this.precoVenda = precoVenda;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getRegistaProdutos() {
        return this.registaProdutos;
    }
    
    public void setRegistaProdutos(Set registaProdutos) {
        this.registaProdutos = registaProdutos;
    }
    public Set getMovimentoVendas() {
        return this.movimentoVendas;
    }
    
    public void setMovimentoVendas(Set movimentoVendas) {
        this.movimentoVendas = movimentoVendas;
    }
    public Set getProdInvents() {
        return this.prodInvents;
    }
    
    public void setProdInvents(Set prodInvents) {
        this.prodInvents = prodInvents;
    }
    public Set getProdutoFornecedors() {
        return this.produtoFornecedors;
    }
    
    public void setProdutoFornecedors(Set produtoFornecedors) {
        this.produtoFornecedors = produtoFornecedors;
    }
    public Set getProdutoEncomendas() {
        return this.produtoEncomendas;
    }
    
    public void setProdutoEncomendas(Set produtoEncomendas) {
        this.produtoEncomendas = produtoEncomendas;
    }
    public Set getMovimentoReposicaos() {
        return this.movimentoReposicaos;
    }
    
    public void setMovimentoReposicaos(Set movimentoReposicaos) {
        this.movimentoReposicaos = movimentoReposicaos;
    }




}


