package BLL;
// Generated 14/set/2017 0:29:34 by Hibernate Tools 4.3.1



/**
 * ProdutoFornecedorId generated by hbm2java
 */
public class ProdutoFornecedorId  implements java.io.Serializable {


     private int produtoId;
     private int fornecedorId;

    public ProdutoFornecedorId() {
    }

    public ProdutoFornecedorId(int produtoId, int fornecedorId) {
       this.produtoId = produtoId;
       this.fornecedorId = fornecedorId;
    }
   
    public int getProdutoId() {
        return this.produtoId;
    }
    
    public void setProdutoId(int produtoId) {
        this.produtoId = produtoId;
    }
    public int getFornecedorId() {
        return this.fornecedorId;
    }
    
    public void setFornecedorId(int fornecedorId) {
        this.fornecedorId = fornecedorId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProdutoFornecedorId) ) return false;
		 ProdutoFornecedorId castOther = ( ProdutoFornecedorId ) other; 
         
		 return (this.getProdutoId()==castOther.getProdutoId())
 && (this.getFornecedorId()==castOther.getFornecedorId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getProdutoId();
         result = 37 * result + this.getFornecedorId();
         return result;
   }   


}


