package BLL;
// Generated 13/set/2017 17:26:29 by Hibernate Tools 4.3.1



/**
 * ProdutoFornecedor generated by hbm2java
 */
public class ProdutoFornecedor  implements java.io.Serializable {


     private int produtoFornecedorId;
     private Fornecedor fornecedor;
     private Produto produto;
     private Float precoCompra;

    public ProdutoFornecedor() {
    }

	
    public ProdutoFornecedor(int produtoFornecedorId) {
        this.produtoFornecedorId = produtoFornecedorId;
    }
    public ProdutoFornecedor(int produtoFornecedorId, Fornecedor fornecedor, Produto produto, Float precoCompra) {
       this.produtoFornecedorId = produtoFornecedorId;
       this.fornecedor = fornecedor;
       this.produto = produto;
       this.precoCompra = precoCompra;
    }
   
    public int getProdutoFornecedorId() {
        return this.produtoFornecedorId;
    }
    
    public void setProdutoFornecedorId(int produtoFornecedorId) {
        this.produtoFornecedorId = produtoFornecedorId;
    }
    public Fornecedor getFornecedor() {
        return this.fornecedor;
    }
    
    public void setFornecedor(Fornecedor fornecedor) {
        this.fornecedor = fornecedor;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Float getPrecoCompra() {
        return this.precoCompra;
    }
    
    public void setPrecoCompra(Float precoCompra) {
        this.precoCompra = precoCompra;
    }




}


