package BLL;
// Generated 13/set/2017 17:26:29 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Recibo generated by hbm2java
 */
public class Recibo  implements java.io.Serializable {


     private int reciboId;
     private Entidade entidade;
     private Venda venda;
     private Float valor;
     private Date data;

    public Recibo() {
    }

	
    public Recibo(int reciboId) {
        this.reciboId = reciboId;
    }
    public Recibo(int reciboId, Entidade entidade, Venda venda, Float valor, Date data) {
       this.reciboId = reciboId;
       this.entidade = entidade;
       this.venda = venda;
       this.valor = valor;
       this.data = data;
    }
   
    public int getReciboId() {
        return this.reciboId;
    }
    
    public void setReciboId(int reciboId) {
        this.reciboId = reciboId;
    }
    public Entidade getEntidade() {
        return this.entidade;
    }
    
    public void setEntidade(Entidade entidade) {
        this.entidade = entidade;
    }
    public Venda getVenda() {
        return this.venda;
    }
    
    public void setVenda(Venda venda) {
        this.venda = venda;
    }
    public Float getValor() {
        return this.valor;
    }
    
    public void setValor(Float valor) {
        this.valor = valor;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }




}


