package BLL;
// Generated 14/set/2017 0:29:34 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Recibo generated by hbm2java
 */
public class Recibo  implements java.io.Serializable {


     private Integer reciboId;
     private Entidade entidade;
     private Venda venda;
     private Float valor;
     private Date data;

    public Recibo() {
    }

    public Recibo(Entidade entidade, Venda venda, Float valor, Date data) {
       this.entidade = entidade;
       this.venda = venda;
       this.valor = valor;
       this.data = data;
    }
   
    public Integer getReciboId() {
        return this.reciboId;
    }
    
    public void setReciboId(Integer reciboId) {
        this.reciboId = reciboId;
    }
    public Entidade getEntidade() {
        return this.entidade;
    }
    
    public void setEntidade(Entidade entidade) {
        this.entidade = entidade;
    }
    public Venda getVenda() {
        return this.venda;
    }
    
    public void setVenda(Venda venda) {
        this.venda = venda;
    }
    public Float getValor() {
        return this.valor;
    }
    
    public void setValor(Float valor) {
        this.valor = valor;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }




}


