package BLL;
// Generated 13/set/2017 17:26:29 by Hibernate Tools 4.3.1



/**
 * RegistaProduto generated by hbm2java
 */
public class RegistaProduto  implements java.io.Serializable {


     private RegistaProdutoId id;
     private Produto produto;
     private Regista regista;
     private Integer quantidade;

    public RegistaProduto() {
    }

	
    public RegistaProduto(RegistaProdutoId id, Produto produto, Regista regista) {
        this.id = id;
        this.produto = produto;
        this.regista = regista;
    }
    public RegistaProduto(RegistaProdutoId id, Produto produto, Regista regista, Integer quantidade) {
       this.id = id;
       this.produto = produto;
       this.regista = regista;
       this.quantidade = quantidade;
    }
   
    public RegistaProdutoId getId() {
        return this.id;
    }
    
    public void setId(RegistaProdutoId id) {
        this.id = id;
    }
    public Produto getProduto() {
        return this.produto;
    }
    
    public void setProduto(Produto produto) {
        this.produto = produto;
    }
    public Regista getRegista() {
        return this.regista;
    }
    
    public void setRegista(Regista regista) {
        this.regista = regista;
    }
    public Integer getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(Integer quantidade) {
        this.quantidade = quantidade;
    }




}


