package BLL;
// Generated 13/set/2017 17:26:29 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Regista generated by hbm2java
 */
public class Regista  implements java.io.Serializable {


     private int registaId;
     private Funcionario funcionario;
     private Integer quantidadeTotal;
     private Date data;
     private Set registaProdutos = new HashSet(0);

    public Regista() {
    }

	
    public Regista(int registaId) {
        this.registaId = registaId;
    }
    public Regista(int registaId, Funcionario funcionario, Integer quantidadeTotal, Date data, Set registaProdutos) {
       this.registaId = registaId;
       this.funcionario = funcionario;
       this.quantidadeTotal = quantidadeTotal;
       this.data = data;
       this.registaProdutos = registaProdutos;
    }
   
    public int getRegistaId() {
        return this.registaId;
    }
    
    public void setRegistaId(int registaId) {
        this.registaId = registaId;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Integer getQuantidadeTotal() {
        return this.quantidadeTotal;
    }
    
    public void setQuantidadeTotal(Integer quantidadeTotal) {
        this.quantidadeTotal = quantidadeTotal;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Set getRegistaProdutos() {
        return this.registaProdutos;
    }
    
    public void setRegistaProdutos(Set registaProdutos) {
        this.registaProdutos = registaProdutos;
    }




}


