package BLL;
// Generated 14/set/2017 0:29:34 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Reposicao generated by hbm2java
 */
public class Reposicao  implements java.io.Serializable {


     private Integer reposicaoId;
     private Funcionario funcionario;
     private Date data;
     private Set movimentoReposicaos = new HashSet(0);

    public Reposicao() {
    }

    public Reposicao(Funcionario funcionario, Date data, Set movimentoReposicaos) {
       this.funcionario = funcionario;
       this.data = data;
       this.movimentoReposicaos = movimentoReposicaos;
    }
   
    public Integer getReposicaoId() {
        return this.reposicaoId;
    }
    
    public void setReposicaoId(Integer reposicaoId) {
        this.reposicaoId = reposicaoId;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Set getMovimentoReposicaos() {
        return this.movimentoReposicaos;
    }
    
    public void setMovimentoReposicaos(Set movimentoReposicaos) {
        this.movimentoReposicaos = movimentoReposicaos;
    }




}


