package BLL;
// Generated 13/set/2017 17:26:29 by Hibernate Tools 4.3.1



/**
 * TipoInventario generated by hbm2java
 */
public class TipoInventario  implements java.io.Serializable {


     private int inventarioId;
     private String desc;

    public TipoInventario() {
    }

	
    public TipoInventario(int inventarioId) {
        this.inventarioId = inventarioId;
    }
    public TipoInventario(int inventarioId, String desc) {
       this.inventarioId = inventarioId;
       this.desc = desc;
    }
   
    public int getInventarioId() {
        return this.inventarioId;
    }
    
    public void setInventarioId(int inventarioId) {
        this.inventarioId = inventarioId;
    }
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }




}


