package BLL;
// Generated 14/set/2017 0:29:34 by Hibernate Tools 4.3.1



/**
 * TipoInventario generated by hbm2java
 */
public class TipoInventario  implements java.io.Serializable {


     private Integer inventarioId;
     private String desc;

    public TipoInventario() {
    }

    public TipoInventario(String desc) {
       this.desc = desc;
    }
   
    public Integer getInventarioId() {
        return this.inventarioId;
    }
    
    public void setInventarioId(Integer inventarioId) {
        this.inventarioId = inventarioId;
    }
    public String getDesc() {
        return this.desc;
    }
    
    public void setDesc(String desc) {
        this.desc = desc;
    }




}


