package BLL;
// Generated 14/set/2017 0:29:34 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Venda generated by hbm2java
 */
public class Venda  implements java.io.Serializable {


     private Integer vendaId;
     private Cliente cliente;
     private Funcionario funcionario;
     private Float preco;
     private Date data;
     private Set recibos = new HashSet(0);
     private Set movimentoVendas = new HashSet(0);

    public Venda() {
    }

    public Venda(Cliente cliente, Funcionario funcionario, Float preco, Date data, Set recibos, Set movimentoVendas) {
       this.cliente = cliente;
       this.funcionario = funcionario;
       this.preco = preco;
       this.data = data;
       this.recibos = recibos;
       this.movimentoVendas = movimentoVendas;
    }
   
    public Integer getVendaId() {
        return this.vendaId;
    }
    
    public void setVendaId(Integer vendaId) {
        this.vendaId = vendaId;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Funcionario getFuncionario() {
        return this.funcionario;
    }
    
    public void setFuncionario(Funcionario funcionario) {
        this.funcionario = funcionario;
    }
    public Float getPreco() {
        return this.preco;
    }
    
    public void setPreco(Float preco) {
        this.preco = preco;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public Set getRecibos() {
        return this.recibos;
    }
    
    public void setRecibos(Set recibos) {
        this.recibos = recibos;
    }
    public Set getMovimentoVendas() {
        return this.movimentoVendas;
    }
    
    public void setMovimentoVendas(Set movimentoVendas) {
        this.movimentoVendas = movimentoVendas;
    }




}


